language: python
python:
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DJANGO=1.9
  - DB=sqlite
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - ./manage.py test
notifications:
 slack: andela:AmE44rzEwEFIoWaF8Z6M4pwQ
  on_failure: always
after_success: coveralls
cache: pip
