# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
    ]