# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180703_1212'),
        ('accounts', '0008_auto_20180703_0928'),
    ]

    operations = [
    ]