# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180711_1206'),
        ('accounts', '0009_merge_20180704_1359'),
    ]

    operations = [
    ]
