# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180704_1359'),
        ('accounts', '0009_merge_20180713_1337'),
    ]

    operations = [
    ]