# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180717_1603'),
        ('accounts', '0010_merge_20180714_0612'),
    ]

    operations = [
    ]
