# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180714_0612'),
        ('accounts', '0010_merge_20180712_1640'),
    ]

    operations = [
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> [Chore #158174602] Synced migrations with develop branch
