# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20180716_1253'),
        ('accounts', '0011_merge_20180717_1824'),
        ('accounts', '0011_auto_20180718_1837'),
    ]

    operations = [
    ]
