# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20180716_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ping_log_limit',
            field=models.IntegerField(default=100),
        ),
    ]
