# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180714_0612'),
        ('accounts', '0011_auto_20180716_1304'),
    ]

    operations = [
    ]
