# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20180717_1332'),
        ('accounts', '0011_merge_20180716_1253'),
    ]

    operations = [
    ]
