# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_backups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backups',
            new_name='Backup',
        ),
    ]
