# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180718_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='date_run',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
