# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180628_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'),
                                            ('webhook', 'Webhook'),
                                            ('hipchat', 'HipChat'),
                                            ('slack', 'Slack'),
                                            ('pd', 'PagerDuty'),
                                            ('po', 'Pushover'),
                                            ('victorops', 'VictorOps'),
                                            ('twiliosms', 'TwilioSms'),
                                            ('twiliovoice', 'TwilioVoice')],
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='value',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]