# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180627_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='nag_after',
            new_name='nag_after_time',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='nag_interval',
            new_name='nag_intervals',
        ),
    ]