# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180629_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='value',
            field=models.TextField(default='+256705357610', max_length=25),
        ),
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(default='+256705357610'),
        ),
    ]
