# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180627_0457'),
        ('api', '0031_auto_20180702_0511'),
    ]

    operations = [
    ]