# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20180703_0840'),
        ('api', '0033_merge_20180703_0805'),
    ]

    operations = [
    ]