# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20180703_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_intervals',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
