# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180703_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='shopify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='shopify_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='check',
            name='shopify_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='check',
            name='shopify_password',
            field=models.CharField(blank=True, max_length=500),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> [Chore #158174602] Synced migrations with develop branch
