# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180704_1353'),
        ('api', '0035_auto_20180703_0928'),
    ]

    operations = [
    ]
