# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180703_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
<<<<<<< HEAD
            field=models.CharField(choices=[
                                            ('email', 'Email'),
                                            ('webhook', 'Webhook'),
                                            ('hipchat', 'HipChat'),
                                            ('slack', 'Slack'),
                                            ('pd', 'PagerDuty'),
                                            ('po', 'Pushover'),
                                            ('victorops', 'VictorOps'),
                                            ('twiliosms', 'TwilioSms'),
                                            ('twiliovoice', 'TwilioVoice'),
                                            ('telegram', 'Telegram')],
                                   max_length=20),
=======
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps'), ('twiliosms', 'TwilioSms'), ('twiliovoice', 'TwilioVoice'), ('telegram', 'Telegram')], max_length=20),
>>>>>>> 736d560a74129020aa74a3b4835fe3967949f814
        ),
    ]
