# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180706_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='chat_id',
            field=models.TextField(default='549751449'),
        ),
    ]
