# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_check_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(default=256705357610),
        ),
    ]
