
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_check_runs_too_often'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='runs_too_often',
            field=models.BooleanField(default=False),
        ),
    ]
