# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180704_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.IntegerField(default=8),
        ),
    ]
