# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180703_0928'),
        ('api', '0038_check_runs_too_often'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('task_type', models.CharField(
                    choices=[
                        (b'database_backups', b'database_backups'),
                        (b'export_reports', b'export_reports')],
                    max_length=100)),
                ('profile', models.ManyToManyField(to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('send_email_updates', models.BooleanField(default=False)),
                ('next_run_time', models.DateTimeField()),
                ('frequency', models.CharField(
                    choices=[
                        (b'daily', b'daily'),
                        (b'weekly', b'weekly'),
                        (b'monthly', b'monthly')],
                    max_length=20)),
                ('run_count', models.IntegerField(default=0)),
                ('task', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.Task')),
            ],
        ),
    ]
