# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180704_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='priority',
        ),
    ]
