# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_task_taskschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='frequency',
            field=models.CharField(
                choices=[
                    (b'daily',
                     b'Daily'),
                    (b'weekly',
                     b'Weekly'),
                    (b'monthly',
                     b'Monthly')],
                default=b'daily',
                max_length=20),
        ),
    ]
