
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_check_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]