# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180712_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(
                choices=[
                    (b'database_backups',
                     b'Database_backups'),
                    (b'export_reports',
                     b'Export_Reports')],
                default=b'database_backups',
                max_length=100),
        ),
    ]
