# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180716_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='next_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
