# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 18:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_check_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='n_nags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='protocol',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterIndexTogether(
            name='check',
            index_together=set([('status', 'user', 'alert_after', 'protocol',
                                 'n_nags')]),
        ),
    ]
