# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_taskschedule_next_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='next_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
