# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0046_auto_20180706_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(blank=True, default=b'+00000000000',
                                   null=True),
        ),
        migrations.AlterIndexTogether(
            name='check',
            index_together=set([('status', 'user', 'alert_after', 'n_nags')]),
        ),
    ]
