# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_check_runs_too_often'),
        ('api', '0048_remove_check_protocol'),
        ('api', '0036_merge_20180713_1337'),
    ]

    operations = [
    ]
