
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_check_runs_too_often'),
        ('api', '0048_remove_check_protocol'),
    ]

    operations = [
    ]
