# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_check_departments'),
        ('api', '0049_auto_20180712_0611'),
    ]

    operations = [
    ]
