# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180712_0611'),
        ('api', '0041_auto_20180713_0817'),
    ]

    operations = [
    ]
