# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180712_0611'),
        ('api', '0036_merge_20180711_1206'),
    ]

    operations = [
    ]
