# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20180713_1209'),
        ('api', '0049_merge_20180716_0857'),
    ]

    operations = [
    ]
