# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180717_1535'),
        ('api', '0049_merge_20180713_1209'),
        ('api', '0036_merge_20180713_1337'),
    ]

    operations = [
    ]
