# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20180716_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('video_link', models.URLField(
                    help_text='https://www.youtube.com/watch?v=5sMKX22BHeEM')),
            ],
        ),
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(
                blank=True, default='+00000000000', null=True),
        ),
    ]
