<<<<<<< HEAD
=======

>>>>>>> [Chore #158174602] Synced migrations with develop branch
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_20180711_1206'),
        ('api', '0050_merge_20180716_0922'),
    ]

    operations = [
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> [Chore #158174602] Synced migrations with develop branch
