# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20180716_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
