# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20180717_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='chat_id',
            field=models.TextField(default='549751449'),
        ),
    ]
