# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_check_check_owner'),
        ('api', '0051_merge_20180716_1254'),
    ]

    operations = [
    ]
