# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180719_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(),
        ),
    ]
