# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20180712_1643'),
        ('api', '0051_merge_20180716_1254'),
    ]

    operations = [
    ]
