# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20180716_0922'),
        ('api', '0051_check_chat_id'),
    ]

    operations = [
    ]
