# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180718_1837'),
        ('api', '0052_merge_20180717_1824'),
        ('api', '0051_merge_20180716_1254'),
    ]

    operations = [
    ]
