# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180717_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('check_assigned', models.ForeignKey(on_delete=django.db.
                                                     models.deletion.CASCADE,
                                                     to='api.Check')),
            ],
        ),
    ]
