# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_merge_20180718_0911'),
        ('api', '0052_auto_20180723_1254'),
    ]

    operations = [
    ]
