# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_merge_20180719_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(default=256705357610),
        ),
    ]
