# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20180719_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='twilio_number',
            field=models.TextField(null=True),
        ),
    ]
